// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import OrderCountController from "./order_count_controller.js"
application.register("order-count", OrderCountController)

import OrderSubmitController from "./order_submit_controller.js"
application.register("order-submit", OrderSubmitController)
